### ISSUE TITLE
Blank Screen on Arch Wayland

### ISSUE THREAD

**Issue by CommanderGL** [ArmCord/ArmCord#638] opened 2024-06-25 01:11 UTC
**Describe the bug**
Whenever I try to open armcord I get an empty window except for the titlebar and close button.

**To Reproduce**
1. Open Armcord on Arch Linux Wayland (I'm using hyprland)

**Expected behavior**
Armcord opnes properly.

**Screenshots**

![Screenshot_2024-06-24_18 08 47](https://github.com/ArmCord/ArmCord/assets/85912189/817faf1f-f31e-46a9-9d2f-875c723ac9c3)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR
 - Version: armcord-bin - 3.2.7-1

**Comment by SomeAspy** [comment] 2024-06-25 02:01
I have a similar problem @ [344f01f](https://github.com/ArmCord/ArmCord/commit/344f01f136e76ea2512b337f9f275f9dd52f6471) on the dev branch. 

Does closing it from tray and re-opening fix for you? Occasionally this happens to me and if I start it again it will work.

Of course, this isn't a solution, but something to look into.

**Comment by aidan-gibson** [comment] 2024-06-26 16:36
Had the same issue with AUR/armcord-git (running hyprland). I deleted `~/.config/armcord` and `~/.config/Armcord` then ran `armcord` from terminal, selecting yes to systray option. This time it wasn't blank, it was eternally "loading" or something. It quit it one more time and re-ran it, it opened fine. If that doesn't work for you, post the output you get from running `armcord` in terminal.

**Comment by smartfrigde** [comment] 2024-06-27 19:24
If there's custom titlebar then that means everything on ArmCord's side went right, it's just Discord that won't load for some reason. Only on X11 I can reproduce ArmCord starting as blank window (with no titlebar) and crashing after few seconds however that seems to be Electron renderer crash.

Any logs (from terminal/console [CTRL+SHIFT+I] would be greatly appreciated.

**Comment by SomeAspy** [comment] 2024-08-12 20:47
Gonna close this as stale as:
- We have incremented to 3.2.8
- We have not received a response from you
 Feel free to comment if you still have the issue.

**Closed by SomeAspy** 2024-08-12 20:47 UTC
Labels: bug
